# Generated by Django 3.1.2 on 2020-11-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201102_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='photo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
