# Generated by Django 3.1.2 on 2020-11-02 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profile_current_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_city',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main_app.city'),
        ),
    ]
